<?php

require_once "/database/DataObject.class.php";

class OrderOnsiteInterpreter extends DataObject {

	protected $data = array(
	    "autoID" => "",
	    "orderID" => "",
	    "customer_id" => "",
	    "invoice_id" => "",
	    "timezone" => "",
	    "assg_frm_date" => "",
	    "assg_frm_st" => "",
	    "assg_frm_en" => "",
	    "assg_to_date" => "",
	    "assg_frm_timestamp" => "",
	    "assg_to_timestamp" => "",
	    "assg_to_st" => "",
	    "assg_to_en" => "",
	    "interpreting_dur" => "",
	    "scheduling_type" => "",
	    "frm_lang" => "",
	    "to_lang" => "",
	    "service_region" => "",
	    "service_area" => "",
	    "dist_frm_reg_srvc_area" => "",
	    "street_address" => "",
	    "address_line_2" => "",
	    "city" => "",
	    "state" => "",
	    "zip" => "",
	    "country" => "",
	    "onsite_con_name" => "",
	    "onsite_con_phone" => "",
	    "onsite_con_email" => "",
	    "candidate_name" => "",
	    "candidate_confirmation_num" => "",
	    "interpreting_type" => "",
	    "equip_needed" => "",
	    "headsets_needed" => "",
	    "intr_needed_for" => "",
	    "description" => "",
	    "t_and_c" => "",
	    "status" => "",
	    "amount" => "",
	    "order_summary_html" => "",
	    "additional_fee" => "",
	    "additional_fee_desc" => "",
	    "overage_charge" => "",
	    "overage_status" => "",
	    "overage_payment_id" => "",
	    "currency_code" => "",
	    "pay_transaction_id" => "",
	    "interpretation_status" => "",
	    "time_taken_complete" => "",
	    "interpreter_id" => "",
	    "interpreter_amt" => "",
	    "overage_amt_per_30min" => "",
	    "overage_interpreter_amt" => "",
	    "ip_note" => "",
	    "admin_note" => "",
	    "notification_24" => "",
	    "notification_day_off" => "",
	    "notification_completion" => "",
	    "notification_checkout" => "",
	    "telephonic_linguists_cj" => "",
	    "mail_sent_to_telephonic_linguists" => "",
	    "deleted" => "",
	    "project_submitted" => "",
	);
}